### ISSUE TITLE
How can I generate the training data?

### ISSUE THREAD

**Issue by xhlbetter** [lhyfst/DSFNet#4]
hi，I want to know how to generate the training data,too? Or is it possible for you to share training datasets?

**Comment by lhyfst** [comment]
We use 300W-LP as the training set. Please refer to [SADRNet](https://github.com/MCG-NJU/SADRNet) for data preprocessing. Our training framework, and data preprocessing and augmentation are very similar to theirs. 
It is not convenient to share the preprocessed training dataset, because after preprocessing, the data takes ~100G of disk space.
